### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by kbrsh** [ripoffgames/ripoffgames.github.io#2]
First of all, why do you guys keep inviting me to join this?

Second, most of your "modded games" are just iframes of their originals, please explain.

:-1:

**Comment by ghost** [comment]
True, all of these companies can sue you.

**Comment by ripoffgames** [comment]
Yes and no

**Comment by ripoffgames** [comment]
If you go to any website like slitheriomods.org, they have an embedded version of slither.io

**Comment by ripoffgames** [comment]
What I think I can do is create a downloadable script using Github zipball and make a download button out of it

**Comment by ripoffgames** [comment]
Though are still working on that feature

**Comment by ripoffgames** [comment]
Plus we have an Apache 2.0 License

**Comment by ripoffgames** [comment]
That pretty much backs any legal work

**Comment by ripoffgames** [comment]
First of all, why do you guys keep inviting me to join this?

We want to constantly find ways to make our website better than what it is. You are the best at that. 

Katie, do u want me to take the invite out, cause I can.

**Comment by kbrsh** [comment]
My name isn't "Katie", and the Apache 2.0 License makes it worse, since you are re-licensing work.

Its fine if you use iframes, I just wanted to know the point of the website itself.

**Comment by ripoffgames** [comment]
I officially hate autocorrect

**Comment by ripoffgames** [comment]
I put in Kabir and it corrects to Katie

**Comment by ripoffgames** [comment]
The point of the website is just to have fun

**Comment by kbrsh** [comment]
Sorry if this comes a little mean, but I don't think I can help you guys.

I have a lot of projects to contribute to, these projects are used by hundreds if not thousands of developers around the world. So I don't really have time to contribute to some random website where the point is to have fun.

Next, maybe if you answer these questions, then I will be able to help out.

1) What text editor do you use?
2) Do you use the Github GUI or CLI?
3) What type of versioning do you use? Your current release is "450 Commit Mark!!", this is not Semantic versioning, like you are supposed to do. How do you expect people to understand?
4) You guys don't have a clear goal for the website, just iframes of games, nothing else, you guys are supposed to mod games. What is your goal?

Thanks
- KingPixil

**Comment by ripoffgames** [comment]
1. We used GitHub pages for the updates page located at
   ripoffgames.github.io/updates. There were some things I didn't like so I
   copied the source code, edited it, and then published it on
   ripoffgames.github.io
2. We use GitHub CLI, I do it on my mac's terminal
3. I just wanted to point out that we reached 450 commits in a short amount
   of time. All updates are mentioned on the website under the "News on RipOff
   Games" section. We don't really use versioning. It's more like milestones.
4. You see, it's pretty, pretty hard to get the source code for complex
   websites. All you get is HTML, CSS, and JS files plus anything else linked.
   So if you have separate files for things like we do, it would be hard to
   access all of them and then build on top of that. Maybe we can just do a JS
   extension that you can download using GitHub Zipball however it's not
   finalized yet. Our goal is to pretty much deliver games to people. If you
   would like to criticize us and tell us that we'll fail, go ahead and I will
   close this issue on GitHub.

I hope this answers all of your questions

Shreyas Lad
RipOff Games

**Comment by ripoffgames** [comment]
Hey by the way,

I'm making a game on iOS. You know, an app. I'll let u know when I get a
developer license from apple so that I can publish it on the App Store

**Comment by kbrsh** [comment]
Hey,

You didn't answer number 1 clearly, how do you edit files, what software do you use? (ex: Notepad)

It is hard to get the source code for complex websites, because they are not **open source**, please search that up. It is when a person releases their website's source code online, usually on Github. That is what Github is used for. Do you think you can find Facebook's code online, and copy and sell it as your own? If it was that easy then we all would have been copying company's source code. The code that is not available to you are the **back-end languages** which handle the servers, socket connection, routing, errors, panics, database, and many other things. This is the part of a web app which crunches numbers and data, like all of the players on a game such as Slither or Agar. They are **not** available to you in any way, or to anyone else for that matter. Check out web apps I make, for example 
- [Lock](https://github.com/KingPixil/lock) - self destructing messages - HTML/CSS/JS Frontend, Node.js Backend, SQLite database
- [Snip](https://github.com/KingPixil/snip) - URL shortener - HTML/CSS/JS Frontend, Go Backend, SQL Database

Please look at their source code to see what I am talking about.

To accomplish what you are trying to do, you need to use a chrome extension that other people use to edit the game's code, search how to make a Slither bot for more information.

I am not trying to criticize you in any way. Sorry if it seems like it, I am only trying to help :smile:

**Comment by ripoffgames** [comment]
Thx bro

**Comment by ripoffgames** [comment]
I edit files directly in the master branch on GitHub. Sid however, uses
notepad to edit his files before publishing. I don't know why.

**Comment by ripoffgames** [comment]
I have one question for you: Do you know Go-Lang, Objective-C, or Swift?

**Comment by ripoffgames** [comment]
Go-Lang is Google's web development language. Basically, if you search up
Google Script, the first link will take you to a Go-Lang editor. From
there, you can try to convert your frameworks into Go-Lang and deploy it as
an extension on the Chrome Web Store

**Comment by kbrsh** [comment]
See, I cannot help if you use the github GUI, you need to use a text editor and then use CLI to push changes, it is much more efficient that way.

If you read my message above, and looked at the projects I made, one actually uses **Go**, trust me I know what it is, please click on the links in the message above and look at their descriptions...

**Comment by ripoffgames** [comment]
Okay okay

**Comment by kbrsh** [comment]
Please give a more detailed response.

Edit: If you want to ask more questions, check out [My AMA](https://github.com/KingPixil/ama) and scroll down, and read.

**Comment by ripoffgames** [comment]
See, I cannot help if you use the Github GUI. We use CLI, not GUI

**Comment by kbrsh** [comment]
What?

**Comment by ripoffgames** [comment]
Sry. Should have quoted. We use CLI, you said we use GUI

**Comment by ripoffgames** [comment]
Fuggedaboutit. I'm doing app development now. My first one is coming out on
Saturday. Ima leave web development to Sid.

**Comment by kbrsh** [comment]
I never said I use GUI, I use CLI.

What is this app you are making?

**Comment by ripoffgames** [comment]
Game. Trying to publish on App Store.
