### ISSUE TITLE
Complete Beta Test Form and iFrame onto website

### ISSUE THREAD

**Issue by ripoffgames** [ripoffgames/ripoffgames.github.io#3]
Complete instructions.html and form.htm [barebones]
Add CSS

Closed Beta Testing of _Defend Space_

**Comment by kbrsh** [comment]
I didn't get the "validation code" for your app

**Comment by ripoffgames** [comment]
I'm not at home right now. It's not automatic. I email people myself

**Comment by kbrsh** [comment]
ok
